stages:
  - build
  - deploy
build-war:
  stage: build
  tags: 
    - shell
    - kinnara

  script:
    - cd "${CI_PROJECT_DIR}"/wflow-app && sh kecak_make.sh
  artifacts:
    paths:
      - wflow-consoleweb/target/kecak.war
    expire_in: 1 day

build-docker-image:
  stage: deploy
  tags: 
    - kinnara
  before_script:
    - git clone git@gitlab.com:kinnarastudio/docker-image-kecak-workflow.git
    - cp wflow-consoleweb/target/kecak.war "${CI_PROJECT_DIR}"/docker-image-kecak-workflow/kecak.war
    - cd "${CI_PROJECT_DIR}"/docker-image-kecak-workflow
  script:
    - docker build -t kinnaradigitalstudio/kecak-workflow:v1 .
    - docker push kinnaradigitalstudio/kecak-workflow:v1

deploy-to-sandbox:
  stage: deploy
  tags: 
    - kinnara
  script:
    - docker-compose -H "ssh://"${SERVER_USERNAME}"@"${SERVER_HOSTNAME}"" version
