stages:
  - build
  - deploy
build-war:
  image: kinnaradigitalstudio/kecak-builder
  stage: build
  tags: 
    - sandbox
  script:
    - cd "${CI_PROJECT_DIR}"/wflow-app && sh kecak_make.sh
  artifacts:
    paths:
      - wflow-consoleweb/target/kecak.war
    expire_in: 1 day

deploy-to-sandbox:
  stage: deploy
  tags: 
    - sandbox
  image: docker:19.03.12
  before_script:
    - apk update && apk add git
    - docker info
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && ssh-keyscan -H "gitlab.com" > ~/.ssh/known_hosts'
    - git config --global user.email "$GIT_MAIL"
    - git config --global user.name "$GIT_USERNAME"
    - git clone git@gitlab.com:kinnarastudio/docker-image-kecak-workflow.git
    - docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD" --password-stdin docker.io
    - cp wflow-consoleweb/target/kecak.war "${CI_PROJECT_DIR}"/docker-image-kecak-workflow/kecak.war
    - cd "${CI_PROJECT_DIR}"/docker-image-kecak-workflow
  script:
    - docker build -t kinnaradigitalstudio/kecak-workflow:v1 .
    - docker push kinnaradigitalstudio/kecak-workflow:v1
